name: Run LPPLS analysis

on:
  push:
  pull_request:

jobs:
  run-lppls:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c(
          "quantmod","pracma","tseries","urca","lomb",
          "rugarch","boot","forecast"
        ), repos="https://cloud.r-project.org")'
    - name: Run analysis
      run: Rscript lppls_analysis.R
